# Generated by Django 3.2.13 on 2022-05-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0002_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='returning',
            field=models.BooleanField(default=False),
        ),
    ]
